a = input('Digite algo:')
print('O tipo primitivo desse valor é', type(a))
print(' Só tem espaços?', a.isspace())
print('É um número?', a.isalnum())
print('É alfabético?', a.isalpha())
print('É alfanumérico?', a.isalnum())
print('está em maiúsculas?', a.isupper())
print('Está em minúsculas?', a.islower())
print('Ésta capitalizada?', a.istitle())